### ISSUE TITLE
Documentations about Tool Caveats

### ISSUE THREAD

**Issue by RexWzh** [lenianiva/PyPantograph#48]
Hi @lenianiva, I want to express my appreciation for this project and its prospects in ITP. While working with the tool, I found several cases needing attention. 

I think documenting these cases could help improve the project's stability and usability.

Moreover, I suggest using some test tools, like pytest, which could help make the project more robust while also serving as usage examples.

> *Note: Lean seems to have its own development testing setup, as shown in [repl](https://github.com/leanprover-community/repl/tree/master/test). While I haven't used it personally, it might be worth a try.*

Here are the main issues I've found:
1. Type Inference in Goal Start
2. JSON Parser Errors
3. Goal Picking Interaction Conflicts
4. Special Tactics Behavior

## 1. Type Inference in Goal Start

The tool fails with implicit types, particularly with `Nat`:

```python
# Fails - missing type - unsolved proof
state = server.goal_start('1+1=2')
print(server.goal_tactic(state, 0, 'ring'))

# Works - explicit type
state = server.goal_start('(1:Nat)+1=2')
print(server.goal_tactic(state, 0, 'ring'))

# Works - using load_sorry
state, = server.load_sorry('example : 1+ 1 = 2 := by sorry')
print(server.goal_tactic(state, 0, 'ring'))
```

Similar issues occur in more complex cases like this example from [MiniF2F](https://github.com/wzj423/lean-dojo-mew/blob/1ef4e4cac9dd370b7be6d648ce135a06aa6fce5f/MiniF2F/Test.lean#L468):

```python
# unsolved proof
thm = """
theorem amc12a_2020_p7 (a : ℕ → ℕ) (h₀ : a 0 ^ 3 = 1) (h₁ : a 1 ^ 3 = 8) (h₂ : a 2 ^ 3 = 27)
    (h₃ : a 3 ^ 3 = 64) (h₄ : a 4 ^ 3 = 125) (h₅ : a 5 ^ 3 = 216) (h₆ : a 6 ^ 3 = 343) :
    ↑(∑ k in Finset.range 7, 6 * a k ^ 2) - ↑(2 * ∑ k in Finset.range 6, a k ^ 2) = (658 : ℤ) := by
rw [show 1 = 1^3 by norm_num, pow_left_inj ] at h₀ <;> norm_num
rw [show 8 = 2^3 by norm_num, pow_left_inj ] at h₁ <;> norm_num
rw [show 27 = 3^3 by norm_num, pow_left_inj ] at h₂ <;> norm_num
rw [show 64= 4^3 by norm_num, pow_left_inj ] at h₃ <;> norm_num
rw [show 125= 5^3 by norm_num, pow_left_inj ] at h₄ <;> norm_num
rw [show 216= 6^3 by norm_num, pow_left_inj ] at h₅ <;> norm_num
rw [show 343 =7^3 by norm_num, pow_left_inj ] at h₆ <;> norm_num
repeat rw [Finset.sum_range_succ]
sorry
"""

state, = server.load_sorry(thm)
print(server.goal_tactic(state, 0, 'norm_num [h₀,h₁,h₂,h₃,h₄,h₅,h₆]'))
# ⊢ 6 * 1 + 6 * 4 + 6 * 9 + 6 * 16 + 6 * 25 + 6 * 36 + 6 * 49 - 182 = 658
```

## 2. JSON Parser Errors

Parser errors for `{}`:

```python
thm = """
theorem amc12_2000_p15 (f : ℂ → ℂ) (h₀ : ∀ x, f (x / 3) = x ^ 2 + x + 1)
    (h₁ : Fintype (f ⁻¹' {7})) : (∑ y in (f ⁻¹' {7}).toFinset, y / 3) = -1 / 9 := by sorry
"""
server.load_sorry(thm)
```

Another case from Minif2f:

```python
thm = """
theorem mathd_numbertheory_552 (f g h : ℕ+ → ℕ) (h₀ : ∀ x, f x = 12 * x + 7)
    (h₁ : ∀ x, g x = 5 * x + 2) (h₂ : ∀ x, h x = Nat.gcd (f x) (g x)) (h₃ : Fintype (Set.range h)) :
    (∑ k in (Set.range h).toFinset, k) = 12 := by sorry
"""
server.load_sorry(thm)
```

## 3. Goal-Picking Interaction Conflicts

Tactics related to goal operations can fail, such as `swap`, `all_goals`, ~~`interval_cases`~~, etc. These failures might be due to conflicts with Pantograph's goal-picking feature.

Here's a Python function for testing these cases:

```python
from loguru import logger
logger.remove()
default_format = "<green>{level}</green> | <lvl>{message}</lvl>"
logger.add(lambda msg: print(msg, end=''), format=default_format, colorize=True)

def apply_tactics(server, state, tactics, goal_ids=None, display=False):
    states = [state]
    goal_ids = goal_ids or [0] * len(tactics)
    if display: print(state)
    for tactic, goal_id in zip(tactics, goal_ids):
        if display: logger.info(tactic)
        state = server.goal_tactic(states[-1], goal_id, tactic)
        if display:
            if not state.is_solved:
                print(state, end='\n\n')
            else:
                print("close proof")
        states.append(state)
    return states
```

For example, `pick_goal 2` failed

```python
state0 = server.goal_start('∀ (p q: Prop), p ∨ q → q ∨ p')
tactics = [
    'intro p q h',
    'cases h',
    'pick_goal 2', 
    'apply Or.inl',
    'assumption',
    'apply Or.inr',
    'assumption'
]
states = apply_tactics(server, state0, tactics, display=True)
assert states[-1].is_solved
# TacticFailure: ['goal index out of bounds']
```

The `.` block for entering a specific goal can also cause issues:

```python
tactics = [
    'intro p q h',
    'cases h',
    '. apply p', # term ignored & one can do anything here
    'apply Or.inl',
    'assumption', # proof closed
    'apply Or.inr', # failed
    'assumption'
]
states = apply_tactics(server, state0, tactics, display=True)
```
<img width="257" alt="image" src="https://github.com/user-attachments/assets/0e501885-9cde-4cd7-8eac-b4b34afca76a">

Note: The issue reported at https://github.com/lenianiva/Pantograph/issues/1 is related to subgoal handling and remains unfixed as of the latest commit.

## 4. Special Tactics Behavior

Special tactics require the use of standard wrappers like `HaveTactic`. For example:

```python
state0 = server.goal_start('∀ (p q: Prop), p ∨ q → q ∨ p')
tactics = [
    'intro p q',
    'have g: 1+ 1 = 2', 'ring',
    'intro h',
    'cases h',
    'apply p' # failed
]
apply_tactics(server, state0, tactics, display=True)
```
<img width="624" alt="image" src="https://github.com/user-attachments/assets/103678e2-0d75-467b-9ca2-2e5a746d5f12">

**Comment by lenianiva** [comment]
Hi Rex,

1. I don't think its a good idea to allow expressions of ambiguous types like `1 + 1 = 2` to parse through, but if you think its required maybe I can add it as a conditional behaviour
2. Does this work in Lean LSP? If it doesn't, it won't work in Pantograph either, and that's intended. It could be a missing import problem and the syntactic extension not being in the environment.
3. `pick_goal` and `swap` run directly contrary to tree search paradigms so it should not be used at all. Why would `interval_cases` fail? Same thing goes for the `.` (focus) tactic.

The issue you listed in https://github.com/lenianiva/Pantograph/issues/1 is fixed, but there are multiple ways to fix it and you may not like the way I chose, so I'm looking for user import in that issue.
4. `have` is technically speaking not a tactic at all, and it is at least as composite as `conv`. Moreover every time you run `have`, two goals get created, and the user has to clarify which goal to solve first. This makes it unlikely to have a `have` tactic that just looks like a tactic.

**Comment by lenianiva** [comment]
> Moreover, I suggest using some test tools, like pytest, which could help make the project more robust while also serving as usage examples.

The feedback from ML users I received is that I should not rely on using unit tests as usage examples, so I opted for the documentation site generation approach.

> Note: Lean seems to have its own development testing setup, as shown in [repl](https://github.com/leanprover-community/repl/tree/master/test). While I haven't used it personally, it might be worth a try.

There is really not much to test. We have some unit tests attached to the files in `pantograph/{server,search}.py`. All the Lean tests are stored upstream https://git.leni.sh/aniva/Pantograph/src/branch/dev/Test and I have my own testing infrastructure for that.

**Comment by lenianiva** [comment]
Can you reply to point No. 1, 2, 3 to see what kind of behaviour do you like to see with Pantograph? If not, I'll close this issue as a documentation problem after I add a caveats page to the documentation.

**Comment by RexWzh** [comment]
Thank you for the detailed feedback. I'd like to address a few points:

1. You're right about the ambiguous types. The error with `1 + 1 = 2` is more like an expected behavior.

2. When testing theorem loading, I find that the statement [amc12a_2020_p7](https://github.com/wzj423/lean-dojo-mew/commit/d08b8ba9bad48a7a6497bad6fde21bace85128e2#diff-81fe3eff782dd561d0b5689dd7969faa098e7812e6ca5c4ca41ce40fe564f7faR482) raises an error in Lean [LSP](https://live.lean-lang.org/#codez=JYWwDg9gTgLgBASQHbBgKFJWcCyBDGACwBtgAjNNIgU2mpDjxAGMBGAJjwH12AGPrmADsaOHAAUeOAC44gVEI4gJMJ5ASlFwAtBomEZEwABEcAB4AaRsbgA+OLxVqx4woACCPVN5wAegGY4AXjis9jqAgQR6kgEq3n5wABxBjoBBBGFS7JE+/uxC8YSAwQTJcF5p0QBsACzZgCEE+eVR/hwArNmAoQT5jbVw7KzF2YBhBPnd7V6lhTLqgIhEcADWcMBIcABiswDO1DAAdFB4SADm1HBCZuLFcABUElKTkamacICJhOLsp3AT07MLy6sbW7twxYcXVxU0SO9Ri0kAJIRA6T+MgATzg6igAHc4ABtJaECAo1jRVhROFwJDQEBcJAAVxAZkgSK4xGoADMYFxZgArOAAXUY8GccAAPABuaxEqAk8kgREo9GYlExaLsfHw4WiilUrG0hlM1kcrlwQihAVC4mkikStEYrEdITRLwKwlGsWqml0xnMpBszkEXVJA12kXG8ViZFm6W/Ur+Uq2pX+x3ql1aj3cvI+qNi01Si0Nfz1SP2lVwamxzVu7WewhVZO5gNwIPplGdYr+Yo5v0O/Nq51F906wgtCstk2ByXmlFDdJCZvKyltp0a11d0t9PuTxHUMDUT01xZIFbrJYUribHbULh75jMdnqFMUtHOEx6u8JO85O8VO9NO89dlAA), while getting passed in Pantograph. Also, I noticed that both LeanDojo and Pantograph might miss the error message raised by Lean. We should reject these kinds of statements to avoid more errors.

3. I apologize for including `interval_cases` in the list of problematic tactics. This was a version compatibility issue, not a Pantograph-specific problem.

4. I tested the error case in the latest commit of PyPantograph, but missed that `src` was not updated. I'll check it out and make a more thorough inspection and tests.

Now that we are splitting the development of Pypantograph and Pantograph, I suggest removing or updating the submodule structure to facilitate independent development.

**Comment by RexWzh** [comment]
To be clear, my intention with this issue is focused on test and CI requirements, though I could help set up documentation actions as well.

Note that we've already discussed testing at https://github.com/lenianiva/PyPantograph/issues/33. Perhaps we should close this issue and continue tracking there.

It is a sad fact that:
*Researchers aren't very open about what they do and the Lean organization hasn't put much effort into standardizing this.*

It's valuable when developers share their work openly.

Speaking from experience, I've contributed to LeanDojo, adding the [local-repo trace feature](https://github.com/lean-dojo/LeanDojo/releases/tag/v2.1.0), mainly on the Python implementation aspects.

I'd like to submit a Test-CI PR and help track error behavior if needed.

**Comment by lenianiva** [comment]
> Thank you for the detailed feedback. I'd like to address a few points:
> 
>     1. You're right about the ambiguous types. The error with `1 + 1 = 2` is more like an expected behavior.

One very important thing in Lean's kernel is that a declaration is not supposed to have mvars, so if you write `1+1=2` then the type becomes a mvar. We can relax this constraint if you need it, but I don't know what will happen.

>     2. When testing theorem loading, I find that the statement [amc12a_2020_p7](https://github.com/wzj423/lean-dojo-mew/commit/d08b8ba9bad48a7a6497bad6fde21bace85128e2#diff-81fe3eff782dd561d0b5689dd7969faa098e7812e6ca5c4ca41ce40fe564f7faR482) raises an error in Lean [LSP](https://live.lean-lang.org/#codez=JYWwDg9gTgLgBASQHbBgKFJWcCyBDGACwBtgAjNNIgU2mpDjxAGMBGAJjwH12AGPrmADsaOHAAUeOAC44gVEI4gJMJ5ASlFwAtBomEZEwABEcAB4AaRsbgA+OLxVqx4woACCPVN5wAegGY4AXjis9jqAgQR6kgEq3n5wABxBjoBBBGFS7JE+/uxC8YSAwQTJcF5p0QBsACzZgCEE+eVR/hwArNmAoQT5jbVw7KzF2YBhBPnd7V6lhTLqgIhEcADWcMBIcABiswDO1DAAdFB4SADm1HBCZuLFcABUElKTkamacICJhOLsp3AT07MLy6sbW7twxYcXVxU0SO9Ri0kAJIRA6T+MgATzg6igAHc4ABtJaECAo1jRVhROFwJDQEBcJAAVxAZkgSK4xGoADMYFxZgArOAAXUY8GccAAPABuaxEqAk8kgREo9GYlExaLsfHw4WiilUrG0hlM1kcrlwQihAVC4mkikStEYrEdITRLwKwlGsWqml0xnMpBszkEXVJA12kXG8ViZFm6W/Ur+Uq2pX+x3ql1aj3cvI+qNi01Si0Nfz1SP2lVwamxzVu7WewhVZO5gNwIPplGdYr+Yo5v0O/Nq51F906wgtCstk2ByXmlFDdJCZvKyltp0a11d0t9PuTxHUMDUT01xZIFbrJYUribHbULh75jMdnqFMUtHOEx6u8JO85O8VO9NO89dlAA), while getting passed in Pantograph.

I just tested this in Lean v4.12.0 and Mathlib v4.12.0, and the statement passes compilation.
```lean
import Mathlib

theorem amc12a_2020_p7
  (a : ℕ → ℕ)
  -- (h : (∀ x, a x > 0))
  (h₀ : (a 0)^3 = 1)
  (h₁ : (a 1)^3 = 8)
  (h₂ : (a 2)^3 = 27)
  (h₃ : (a 3)^3 = 64)
  (h₄ : (a 4)^3 = 125)
  (h₅ : (a 5)^3 = 216)
  (h₆ : (a 6)^3 = 343) :
  ∑ k in Finset.range 7, (6 * (a k)^2) - ↑(2 * ∑ k in Finset.range 6, (a k)^2) = 658 :=
by
  rw [show 1 = 1^3 by norm_num, pow_left_inj ] at h₀ <;> norm_num
  rw [show 8 = 2^3 by norm_num, pow_left_inj ] at h₁ <;> norm_num
  rw [show 27 = 3^3 by norm_num, pow_left_inj ] at h₂ <;> norm_num
  rw [show 64= 4^3 by norm_num, pow_left_inj ] at h₃ <;> norm_num
  rw [show 125= 5^3 by norm_num, pow_left_inj ] at h₄ <;> norm_num
  rw [show 216= 6^3 by norm_num, pow_left_inj ] at h₅ <;> norm_num
  rw [show 343 =7^3 by norm_num, pow_left_inj ] at h₆ <;> norm_num
  repeat rw [Finset.sum_range_succ]
  norm_num [h₀,h₁,h₂,h₃,h₄,h₅,h₆]
```
so I'd say this is expected. Maybe you're on a different version?

> Also, I noticed that both LeanDojo and Pantograph might miss the error message raised by Lean. We should reject these kinds of statements to avoid more errors.

This has been fixed (Pantograph#1). If you see this behaviour again in v0.2.22 and onwards please notify me ASAP because a soundness bug is of the highest priority.

>     3. I apologize for including `interval_cases` in the list of problematic tactics. This was a version compatibility issue, not a Pantograph-specific problem.

Tactics can in principle operate on multiple goals at once. If this ever becomes a problem, I'll relax the constraint that each tactic is running "shielded" from other goals, but if this becomes true the burden for user's bookkeeping will be much higher.

> Now that we are splitting the development of Pypantograph and Pantograph, ~I suggest removing or updating the submodule structure to facilitate independent development.~ I notice this is already being addressed in the recent PR.

How do you recommend that the structure be reorganized?

> To be clear, my intention with this issue is focused on test and CI requirements, though I could help set up documentation actions as well.

I'm putting these on the side now because I know @Purewhite2019 has an async version of PyPantograph and that could introduce major changes. I'll contact my coauthor Livia to see if she has time to handle the CI and testing.

> Perhaps we should close this issue and continue tracking there.

I'll close it when all caveats are mentioned in the documentation.

> Researchers aren't very open about what they do and the Lean organization hasn't put much effort into standardizing this.

Lean's not engineered to support this use case, and there are many things for an interaction library to watch out for. Even with Pantograph, my main project has to augment it with additional plugins to make it work for my GNNs. I don't think there'll be a universal tool to train every ML agent, and researchers will have to improvise with the ever increasing engineering barrier to MATP.

> I'd like to submit a Test-CI PR and help track error behavior if needed.

Sounds good.

**Comment by lenianiva** [comment]
https://github.com/lenianiva/PyPantograph/pull/50

should address all the concerns here. See `README.md` for instructions on building the documentation.

**Comment by RexWzh** [comment]
The commit fixes the statement. However, the error version still gets accepted during theorem loading - you can verify this in the LSP response [here](https://live.lookeng.cn/#project=4.12.0&codez=JYWwDg9gTgLgBASQHbBgKFJWcCyBDGACwBtgAjNNIgU2mpDjxAGMBGAJjwH12AGPrmADsaOHAAUeOAC44gVEI4gJMJ5ASlFwAtBomEZEwABEcAB4AaRsbgA+OLxVqx4woACCPVN5wAegGY4AXjis9jqAgQR6kgEq3n5wABxBjoBBBGFS7JE+/uxC8YSAwQTJcF5p0QBsACzZgCEE+eVR/hwArNmAoQT5jbVw7KzF2YBhBPnd7V6lhTLqgIhEcADWcMBIcABiswDO1DAAdFB4SADm1HBCZuLFcABUElKTkamacICJhOLsp3AT07MLy6sbW7twxYcXVxU0SO9Ri0kAJIRA6T+MgATzg6igAHc4ABtJaECAo1jRVhROFwJDQEBcJAAVxAZkgSK4xGoADMYFxZgArOAAXUY8GccAAPABuaxEqAk8kgREo9GYlExaLsfHw4WiilUrG0hlM1kcrlwQihAVC4mkikStEYrEdITRLwKwlGsWqml0xnMpBszkEXVJA12kXG8ViZFm6W/Ur+Uq2pX+x3ql1aj3cvI+qNi01Si0Nfz1SP2lVwamxzVu7WewhVZO5gNwIPplGdYr+Yo5v0O/Nq51F906wgtCstk2ByXmlFDdJCZvKyltp0a11d0t9PuTxHUMDUT01xZIFbrJYUribHbULh75jMdnqFMUtHOEx6u8JO85O8VO9NO89dlAA).

Specifically, the RHS of the statement should be `658` rather than `(658 : ℤ)`.

> please notify me ASAP because a soundness bug is of the highest priority.

Get. I'm conducting wider testing as quickly as possible to identify any similar cases.

**Comment by lenianiva** [comment]
> The commit fixes the statement. However, the error version still gets accepted during theorem loading - you can verify this in the LSP response [here](https://live.lookeng.cn/#project=4.12.0&codez=JYWwDg9gTgLgBASQHbBgKFJWcCyBDGACwBtgAjNNIgU2mpDjxAGMBGAJjwH12AGPrmADsaOHAAUeOAC44gVEI4gJMJ5ASlFwAtBomEZEwABEcAB4AaRsbgA+OLxVqx4woACCPVN5wAegGY4AXjis9jqAgQR6kgEq3n5wABxBjoBBBGFS7JE+/uxC8YSAwQTJcF5p0QBsACzZgCEE+eVR/hwArNmAoQT5jbVw7KzF2YBhBPnd7V6lhTLqgIhEcADWcMBIcABiswDO1DAAdFB4SADm1HBCZuLFcABUElKTkamacICJhOLsp3AT07MLy6sbW7twxYcXVxU0SO9Ri0kAJIRA6T+MgATzg6igAHc4ABtJaECAo1jRVhROFwJDQEBcJAAVxAZkgSK4xGoADMYFxZgArOAAXUY8GccAAPABuaxEqAk8kgREo9GYlExaLsfHw4WiilUrG0hlM1kcrlwQihAVC4mkikStEYrEdITRLwKwlGsWqml0xnMpBszkEXVJA12kXG8ViZFm6W/Ur+Uq2pX+x3ql1aj3cvI+qNi01Si0Nfz1SP2lVwamxzVu7WewhVZO5gNwIPplGdYr+Yo5v0O/Nq51F906wgtCstk2ByXmlFDdJCZvKyltp0a11d0t9PuTxHUMDUT01xZIFbrJYUribHbULh75jMdnqFMUtHOEx6u8JO85O8VO9NO89dlAA).
> 
> Specifically, the RHS of the statement should be `658` rather than `(658 : ℤ)`.
> 
> > please notify me ASAP because a soundness bug is of the highest priority.
> 
> Get. I'm conducting wider testing as quickly as possible to identify any similar cases.

I can't open your link on desktop or mobile. Please test the case with `lake lean Example.lean` first before submitting a bug report.
